### ISSUE TITLE
Portfolio link is broken

### ISSUE THREAD

**Issue by florian-lefebvre** [Isaiah-Hamilton/Portfolio#87]
Hi, nice website ! I just noticed a broken link in the Portfolio section, for the Portfolio project. The link is https://github.com/isaiah7hamilton/portfolio and should be https://github.com/Isaiah-Hamilton/Portfolio

**Comment by Isaiah-Hamilton** [comment]
Fix with https://github.com/Isaiah-Hamilton/Portfolio/commit/3037f217b1732a1f81a78562a55970048fdd5c92
